var msg = "Hello typescript";
console.log(msg);
var age = 25;
var Pname = "Soham";
console.log("My name is " + Pname + " and my age is " + age);
var country = "India";
var population = 140;
var isCapital = false;
console.log("Country: ".concat(country, ", Population: ").concat(population, " crores, Is Capital: ").concat(isCapital));
var marks = [90, 20, 30, 40];
var sname = ["Soham", "Rohan", "Kartik", "Neha"];
console.log("Marks: ", marks, "SNames: ", sname);
var Employee = [101, "Soham"];
console.log("Employee ID: ", Employee[0], " Employee Name: ", Employee[1]);
var data = 10;
data = "Soham";
data = true;
console.log("Data: ", data);
var response;
response = 200;
response = "OK";
response = true;
console.log("Response: ", response);
